FROM rhel7

USER 0

#	--enablerepo rhel-7-server-optional-rpms \
RUN \
    rpm -Uhv https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
    yum \
	--enablerepo rhel-7-server-extras-rpms \
	install -y \
	    certbot \
    && \
    yum clean all

COPY req-cert.sh /usr/local/bin

USER 1001
